import { Project, ContactPayload } from '../types';

const API_BASE = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:5000/api';

export const fallbackProjects: Project[] = [
  {
    title: 'The Monolith Residence',
    slug: 'the-monolith-residence',
    category: 'Residential',
    location: 'Kochi, India',
    year: 2026,
    area: '14,500 sq.ft',
    description: 'A monolithic cast-concrete sanctuary cantilevered over an obsidian reflection pool, harmonizing brutalist form with tropical climate ecology.',
    story: 'Designed as a dialogue between weight and weightlessness. The structure features board-formed concrete masses floating above black granite water basins, dissolving boundaries between interior galleries and surrounding lush coconut groves.',
    coverImage: '/images/projects/project-monolith.jpg',
    gallery: [
      '/images/projects/project-monolith.jpg',
      '/images/hero/hero-entrance.jpg',
      '/images/hero/hero-interior.jpg',
    ],
    featured: true,
    order: 1,
    services: ['Architectural Design', 'Interior Architecture', 'Landscape Masterplan', 'Lighting Design'],
  },
  {
    title: 'Aura Cultural Centre',
    slug: 'aura-cultural-centre',
    category: 'Cultural',
    location: 'Bangalore, India',
    year: 2025,
    area: '38,000 sq.ft',
    description: 'A civic landmark sculpted from interlocking geometric stone masses with a grand illuminated glass atrium floating over civic water plazas.',
    story: 'The building acts as an open cultural beacon, orchestrating natural daylight through precision louvers and cooling cross-breezes generated by stepped water courtyards.',
    coverImage: '/images/projects/project-cultural.jpg',
    gallery: [
      '/images/projects/project-cultural.jpg',
      '/images/projects/project-monolith.jpg',
    ],
    featured: true,
    order: 2,
    services: ['Civic Architecture', 'Exhibition Design', 'Acoustic Engineering', 'Sustainable Urbanism'],
  },
  {
    title: 'Kyoto Canopy Villa',
    slug: 'kyoto-canopy-villa',
    category: 'Residential',
    location: 'Kyoto, Japan',
    year: 2025,
    area: '8,200 sq.ft',
    description: 'A minimalist Japanese pavilion fusing charred Shou Sugi Ban cedar, dark architectural steel, and frameless glass framing a meditative Zen rock garden.',
    story: 'Conceived under the Japanese philosophy of Ma (negative space), the residence frames changing seasons through sliding smoked-glass planes, tactile tatami suites, and evening stone illumination.',
    coverImage: '/images/projects/project-kyoto.jpg',
    gallery: [
      '/images/projects/project-kyoto.jpg',
      '/images/hero/hero-interior.jpg',
    ],
    featured: true,
    order: 3,
    services: ['Residential Architecture', 'Zen Landscape Integration', 'Custom Joinery'],
  },
  {
    title: 'Vanguard Commercial Tower',
    slug: 'vanguard-commercial-tower',
    category: 'Commercial',
    location: 'Dubai, UAE',
    year: 2024,
    area: '160,000 sq.ft',
    description: 'A sculptural diagrid skyscraper redefining the desert skyline with spiraling bronze shading ribs, hanging vertical sky courts, and reflective glass.',
    story: 'A testament to high-performance passive cooling and parametric structural engineering. The tower reduces solar heat gain by 42% while providing panoramic views of the Arabian Gulf.',
    coverImage: '/images/projects/project-dubai.jpg',
    gallery: [
      '/images/projects/project-dubai.jpg',
      '/images/projects/project-cultural.jpg',
    ],
    featured: true,
    order: 4,
    services: ['High-Rise Architecture', 'Parametric Engineering', 'LEED Platinum Certification'],
  },
  {
    title: 'Atelier Brutaliste',
    slug: 'atelier-brutaliste',
    category: 'Commercial',
    location: 'Zurich, Switzerland',
    year: 2026,
    area: '19,500 sq.ft',
    description: 'An alpine design laboratory sculpted from raw board-formed concrete and warm bronze fenestrations nestled in the Swiss foothills.',
    story: 'Designed as our central European design laboratory, this building embraces brutalist honesty with tactile thermal mass, continuous glass horizons, and timber model workshops.',
    coverImage: '/images/projects/project-zurich.jpg',
    gallery: [
      '/images/projects/project-zurich.jpg',
      '/images/hero/hero-interior.jpg',
    ],
    featured: true,
    order: 5,
    services: ['Studio Design', 'Passive Solar Architecture', 'Structural Concrete Engineering'],
  },
  {
    title: 'Alisha Coastal Estate',
    slug: 'alisha-coastal-estate',
    category: 'Hospitality',
    location: 'Alibaug, India',
    year: 2025,
    area: '22,000 sq.ft',
    description: 'Low-slung coastal pavilion crafted from local warm sandstone, dark teak colonnades, and stepping-stone reflecting pools touching the Arabian Sea.',
    story: 'Blurring the threshold between land and maritime horizon. Open-air living pavilions and deep cantilevered teak roofs foster natural ventilation while framing sunset vistas.',
    coverImage: '/images/projects/project-alibaug.jpg',
    gallery: [
      '/images/projects/project-alibaug.jpg',
      '/images/hero/hero-entrance.jpg',
    ],
    featured: true,
    order: 6,
    services: ['Hospitality Masterplanning', 'Biophilic Design', 'Landscape Architecture'],
  },
];

export async function fetchProjects(category?: string): Promise<Project[]> {
  const isLocalBackend = !process.env.NEXT_PUBLIC_API_URL || API_BASE.includes('localhost');
  const isServerBuild = typeof window === 'undefined';

  // In production builds without a deployed backend, use offline fallback data directly
  if (process.env.NODE_ENV === 'production' && isServerBuild && isLocalBackend) {
    if (category && category !== 'All') {
      return fallbackProjects.filter((p) => p.category.toLowerCase() === category.toLowerCase());
    }
    return fallbackProjects;
  }

  try {
    const url = new URL(`${API_BASE}/projects`);
    if (category && category !== 'All') {
      url.searchParams.set('category', category);
    }
    const res = await fetch(url.toString(), {
      next: { revalidate: 30 },
      headers: { Accept: 'application/json' },
    });
    if (!res.ok) throw new Error(`HTTP error ${res.status}`);
    const text = await res.text();
    const json = text ? JSON.parse(text) : null;
    return json?.data || fallbackProjects;
  } catch (err) {
    if (category && category !== 'All') {
      return fallbackProjects.filter((p) => p.category.toLowerCase() === category.toLowerCase());
    }
    return fallbackProjects;
  }
}

export async function fetchProjectBySlug(slug: string): Promise<{ project: Project; nextProject?: any }> {
  const isLocalBackend = !process.env.NEXT_PUBLIC_API_URL || API_BASE.includes('localhost');
  const isServerBuild = typeof window === 'undefined';

  if (process.env.NODE_ENV === 'production' && isServerBuild && isLocalBackend) {
    const proj = fallbackProjects.find((p) => p.slug === slug.toLowerCase()) || fallbackProjects[0];
    const idx = fallbackProjects.findIndex((p) => p.slug === proj.slug);
    const nextItem = fallbackProjects[(idx + 1) % fallbackProjects.length];
    return {
      project: proj,
      nextProject: {
        title: nextItem.title,
        slug: nextItem.slug,
        location: nextItem.location,
        coverImage: nextItem.coverImage,
      },
    };
  }

  try {
    const res = await fetch(`${API_BASE}/projects/${slug}`, {
      next: { revalidate: 30 },
      headers: { Accept: 'application/json' },
    });
    if (!res.ok) throw new Error(`HTTP error ${res.status}`);
    const text = await res.text();
    const json = text ? JSON.parse(text) : null;
    return {
      project: json?.data || fallbackProjects[0],
      nextProject: json?.nextProject,
    };
  } catch (err) {
    const proj = fallbackProjects.find((p) => p.slug === slug.toLowerCase()) || fallbackProjects[0];
    const idx = fallbackProjects.findIndex((p) => p.slug === proj.slug);
    const nextItem = fallbackProjects[(idx + 1) % fallbackProjects.length];
    return {
      project: proj,
      nextProject: {
        title: nextItem.title,
        slug: nextItem.slug,
        location: nextItem.location,
        coverImage: nextItem.coverImage,
      },
    };
  }
}

export async function submitContactForm(data: ContactPayload): Promise<{ success: boolean; message: string }> {
  try {
    const res = await fetch(`${API_BASE}/contact`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(data),
    });
    const json = await res.json();
    if (!res.ok) throw new Error(json.message || 'Submission failed');
    return { success: true, message: json.message };
  } catch (err: any) {
    console.error('[API Client] Contact submit error:', err);
    return { success: false, message: err.message || 'An error occurred while submitting.' };
  }
}
